# Generated by Django 5.1.2 on 2024-11-06 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echos', '0001_initial'),
        ('waves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wave',
            name='echo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waves', to='echos.echo'),
        ),
    ]
