# Generated by Django 5.1.2 on 2024-10-25 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('echos', '0001_initial'),
        ('waves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='echo',
            name='wave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waves', to='waves.wave'),
        ),
    ]
