# Generated by Django 5.1.2 on 2024-11-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echo',
            name='content',
            field=models.TextField(max_length=755),
        ),
    ]
